package:
  name: tissuelab.tissuelab
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/VirtualPlants/tissuelab
  git_tag: master

build:
  preserve_egg_dir: True
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.oalab
    - openalea.components
    - numpy
    - scipy
    - matplotlib ==1.5.1
    - vtk
    - tissuelab.cellcomplex
    - tissuelab.timagetk

test:
  imports:
    - timagetk

about:
  home: http://virtualplants.github.io
  license: Cecill License
