package:
  name: tissuelab.tissuelab
  version: nightly

source:
  git_url: https://github.com/VirtualPlants/tissuelab
  git_tag: develop

build:
  preserve_egg_dir: True
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.oalab ==nightly
    - openalea.components ==nightly
    - numpy
    - scipy
    - matplotlib ==1.5.1
    - vtk
    - pillow
    - tissuelab.cellcomplex ==nightly
    - tissuelab.timagetk

test:
  imports:
    - timagetk

about:
  home: http://virtualplants.github.io
  license: Cecill License
