package:
  name: pyqode.qt
  version: "2.10.0"

source:
  fn: pyqode.qt-2.10.0.tar.gz
  url: https://pypi.python.org/packages/d4/15/f1e4f2e12e114e32eb35bc7bd49a67ff94d6b1a0f1471f49ea04aa1e5b56/pyqode.qt-2.10.0.tar.gz
  md5: bd999d85a513c657c3ea4b1dd7e9b0c5
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyqode.qt = pyqode.qt:main
    #
    # Would create an entry point called pyqode.qt that calls pyqode.qt.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyqt <=4.11.4

  run:
    - python
    - pyqt <=4.11.4

test:
  # Python imports
  imports:
    - pyqode
    - pyqode.qt

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pyQode/pyqode.qt
  license: MIT License
  summary: 'Shim library that wraps PyQt5, PyQt4 and PySide'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
