package:
  name: tissuelab.cellcomplex
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/VirtualPlants/cellcomplex
  git_tag: master

build:
  preserve_egg_dir: True
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.components

test:
  imports:
    - openalea.container

about:
  home: http://virtualplants.github.io
license: Cecill License
