package:
  name: tissuelab.timagetk
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/VirtualPlants/timagetk
  git_tag: master

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.sconsx
  run:
    - python
    - setuptools
    - openalea.oalab

test:
  imports:
    - openalea.oalab

about:
  home: http://virtualplants.github.io
  license: Cecill License
