package:
  name: tissuelab.timagetk
  version: dev

source:
  git_url: https://github.com/VirtualPlants/timagetk

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.sconsx
  run:
    - python
    - setuptools
    - openalea.oalab

test:
  imports:
    - openalea.oalab

about:
  home: http://openalea.gforge.inria.fr/
license: Cecill License
