package:
  name: tissuelab.cellcomplex
  version: dev

source:
  git_url: https://github.com/VirtualPlants/cellcomplex
  git_tag: develop

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.components

test:
  imports:
    - openalea.container

about:
  home: http://openalea.gforge.inria.fr/
license: Cecill License
